# Generated by Django 5.2.8 on 2026-05-04 03:49

import django.db.models.deletion
from django.db import migrations, models


def migrate_group_names_to_foreignkey(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Group = apps.get_model('students', 'Group')

    groups = {}
    for student in Student.objects.all():
        group_name = student.group
        if not group_name:
            continue
        if group_name not in groups:
            group_obj = Group.objects.create(name=group_name, curator='Неизвестно')
            groups[group_name] = group_obj.id
        student.group = groups[group_name]
        student.save(update_fields=['group'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('curator', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='clubs',
            field=models.ManyToManyField(blank=True, to='students.club'),
        ),
        migrations.RunPython(migrate_group_names_to_foreignkey),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.group'),
        ),
    ]
